### ISSUE TITLE
multiple xlsx creation silently fails when no implicit close is used

### ISSUE THREAD

**Issue by mmterpstra** [jmcnamara/excel-writer-xlsx#208] opened 2018-04-05 09:31 UTC
Hi,
This might be a but of the module but i'll want to leave it at this repo and if multiple people are bothered by I'll work on reproducing the issue in a minimal test.

Might be related to #77 but also produces partially filled files that are corrupt. if you remove the `$workBook->close();` line the code will start producing defective excel files but will silently continue, maybe warn from the module that the workbook isn't explicitly closed or fix the issue if possible? 

Thanks for the consideration! 
Best Regards mmterpstra

Version info and code below.
```
$ perl --version

This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux-thread-multi

... clipped ...

$ perl -le 'eval "require $ARGV[0]" and print $ARGV[0]->VERSION' Excel::Writer::XLSX
0.88
```

This is the code, for best results use really large tables (dims 50000 by 4000 for example), as a sidenote i use a local folder set by $TMPDIR in the bash env, but this shouldn't be a problem: 
```
#!/usr/bin/perl
use 5.010_000;
use warnings;
use strict;
use POSIX;
use Excel::Writer::XLSX;

#also see http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm#write_string%28_$row,_$column,_$string,_$format_%29
#and http://search.cpan.org/~jmcnamara/Excel-Writer-XLSX/lib/Excel/Writer/XLSX.pm#Example_5
#

if($#ARGV ne 1)
{
print "\n Usage: txt2xls \n Example: txt2xls \"|\" *.psv\n\n";
}


my $wb;
my @files = @ARGV[1..$#ARGV];

my $del;
if($ARGV[0] =~ /\\t|\t/){
        $del="\t";
}else{
      	$del = $ARGV[0];
}

my $ext = ".xlsx";

for my $file (@files){
        my $xlsxfile=$file;
        $xlsxfile=~s/\.tsv$|\.csv$|\.tdv$|\.cdv$|\.txt$//g;
        $xlsxfile.=$ext;
        unlink($xlsxfile);

        open (TXTFILE, "$file") or die "Cannot read '$file', check if file is present... and if specified correctly";
        my $workBook = Excel::Writer::XLSX->new($xlsxfile);
        print "$0: output file written to ${xlsxfile}\n";
        my $workSheets;
        push(@{$workSheets},$workBook->add_worksheet());

        my $colmax=1024;
        while (<TXTFILE>) {
                chomp;
                my @t = split("$del");

                my $col = 0;
                for my $token (@t) {
                        #split to multiple tables if too big
                        if(not(floor($col/$colmax) < scalar(@{$workSheets}) )){
                                push(@{$workSheets},$workBook->add_worksheet());
                        }
                        $workSheets -> [floor($col/$colmax)] -> write_string(($.-1), $col%$colmax, $token);
                        #$workSheets -> [floor($col/$colmax)] -> write(($.-1), $col%$colmax, $token);
                        $col++;
                }
        }
	close(TXTFILE);
        #Without this line corrupt xlsx files are produced
        $workBook->close();
}

```

**Comment by jmcnamara** [comment] 2018-04-05 11:07
You are correct that this is a duplicate of #77 so I'll close this one. You can add a +1 there to get a notification when it is fixed.

**Closed by jmcnamara** 2018-04-05 11:07 UTC
Labels: bug
