### ISSUE TITLE
Chart title/series name fields using named references treated as strings

### ISSUE THREAD

**Issue by davidf-woaf-net** [jmcnamara/excel-writer-xlsx#214] opened 2018-05-22 18:46 UTC
When using the name fields of `$chart->set_title` or `->add_series` with a
formula that consists of a named range, the name becomes the literal
formula string text rather than the evaluated formula.

A work around is to use the undocumented name_formula field, which results in
the warnings documented in #213.

Using the example below, the first chart has a title with the literal text
'=Sheet1!some_named_range', rather than the evaluated value '2':

```perl
#!/usr/bin/perl

use strict;
use Excel::Writer::XLSX;

my $workbook  = Excel::Writer::XLSX->new("$0.xlsx");
my $worksheet = $workbook->add_worksheet();

my $data = [ [ 2,  3,  4,  5,  6,  7 ] ];
$worksheet->write('A1', $data);

$workbook->define_name('Sheet1!some_named_range', '=Sheet1!$A$1');

##
# Error case: using a named range in magic name field is
# interpreted as a string.
#
# workaround: use name_formula (but results in issue #213
my $chart = $workbook->add_chart(type => 'scatter', embedded => 1);
$chart->set_title(name => '=Sheet1!some_named_range');
$chart->add_series(
    name => '=Sheet1!some_named_range',
    categories => '=Sheet1!$A$1:$A$6',
    values => '=Sheet1!$A$1:$A$6',
);
$worksheet->insert_chart('C1', $chart);

##
# Working case (without named range)
my $chart = $workbook->add_chart(type => 'scatter', embedded => 1);
$chart->set_title(name => '=Sheet1!$A$1');
$chart->add_series(
    name => '=Sheet1!$A$1',
    categories => '=Sheet1!$A$1:$A$6',
    values => '=Sheet1!$A$1:$A$6',
);
$worksheet->insert_chart('M1', $chart);

$workbook->close();
```

Environment:
>    Perl version : 5.022001
>    OS name : linux
>    Module versions: Excel::Writer::XLSX 0.98

**Comment by jmcnamara** [comment] 2018-05-22 19:35
Closing as duplicate of #213

**Closed by jmcnamara** 2018-05-22 19:35 UTC
