### ISSUE TITLE
tests fail under strawberry perl 5.36 (dev version)

### ISSUE THREAD

**Issue by shawnlaffan** [jmcnamara/excel-writer-xlsx#284] opened 2023-03-18 09:56 UTC
Cross-ref https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/83

Running tests for Excel::Writer::XLSX produces a slew of error messages that look like the ones below. Final result is 851 subtests failed.

At a guess, one of the dependencies is reporting full paths instead of abbreviated ones.

If you would like a development version of strawberry perl 5.36 to test with then see https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/dev_20230318 

Dependency versions:
```
Archive::Zip 1.68
IO::File 1.51
File::Temp 0.2311
```

Please let me know what other details you need.  

```
Files=1157, Tests=4765, 541 wallclock secs ( 4.41 usr +  3.08 sys =  7.48 CPU)
Result: FAIL
Failed 845/1157 test programs. 851/4765 subtests failed.
gmake: *** [makefile:915: test_dynamic] Error 255
```

```
t/package/xml_writer/sub_write_xml_declaration.t ...... ok

#   Failed test ' _compare_xlsx_files(): Members.'
#   at t/lib/TestFunctions.pm line 356.
#     Structures begin differing at:
#          $got->[0] = 'C:/strawberry_build/env/temp/_Oinl1kVrZ/_rels/.rels'
#     $expected->[0] = '_rels/.rels'
# Looks like you failed 1 test of 1.
t/regression/array_formula01.t ........................
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests

#   Failed test ' _compare_xlsx_files(): Members.'
#   at t/lib/TestFunctions.pm line 356.
#     Structures begin differing at:
#          $got->[0] = 'C:/strawberry_build/env/temp/jY3ogARmGF/_rels/.rels'
#     $expected->[0] = '_rels/.rels'
# Looks like you failed 1 test of 1.
t/regression/array_formula02.t ........................
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
```

**Comment by jmcnamara** [comment] 2023-03-18 14:09
I'll have a look at it.

**Comment by jmcnamara** [comment] 2023-03-18 20:32
Could you give me some basic instructions on how to reproduce this. I downloaded and installed the StrawberryPerl tarball you linked above but it doesn't have a make or nmake or dmake (which I can go find and install but it may be better if you could give me some more exact instructions so that I can identify the issue more quickly).

**Comment by shawnlaffan** [comment] 2023-03-18 20:50
Use ```gmake```.  (Strawberry perl shifted to ```gmake``` a few versions ago).

**Comment by jmcnamara** [comment] 2023-03-18 23:55
I found the issue. It is due to a forward/backward slash directory separator difference between some of the path reported by some of the dependencies. I can put in a fix/workaround for the issue.

Do you know if this is a regression caused by an update in one of the dependencies or has this been there for while?

**Comment by shawnlaffan** [comment] 2023-03-19 02:12
Thanks.  That's good to hear  

It's hard to say what the cause is.  There have been some changes in core modules that might be implicated, as we are applying a few patches to get 5.36 to pass its own tests.  See https://github.com/StrawberryPerl/Perl-Dist-Strawberry/tree/wip_536/share/perl-5.36

It might also be something from 5.34 though, as we have not yet tried building that.

**Comment by shawnlaffan** [comment] 2023-03-19 10:21
See also https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/88

**Comment by jmcnamara** [comment] 2023-03-19 10:44
> See also [StrawberryPerl/Perl-Dist-Strawberry#88](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/88)

Yes. I think that may be the issue. At least the error occurs right after I use File::Find.

Also, I am now getting reports of [failures](http://www.cpantesters.org/cpan/report/39b1a9a7-6fe6-1014-a3d0-dddeefaa1848) on other Windows Perl variants.

Anyway, I am working on a fix that I should have out today.

**Comment by jmcnamara** [comment] 2023-03-19 12:31
There is a fix for this issue making its way through Pause and on its way to CPAN in Excel::Writer::XLSX version 1.11.

You can double check it when it hits the mirrors but it is passing on the Strawberry Perl dev env you provided.

**Closed** 2023-03-19 12:35 UTC
Labels: bug, short term

**Comment by shawnlaffan** [comment] 2023-03-19 20:55
Confirming 1.11 passes on my local instance of 5.36.  This will be in the next dev build of Strawberry perl.  

Thanks for the rapid fix and cpan testers link.
