### ISSUE TITLE
Subtotals not working on LibreOffice, needs explicit table name

### ISSUE THREAD

**Issue by arhak** [jmcnamara/excel-writer-xlsx#275] opened 2022-05-04 22:35 UTC
`Err:508` is shown in LibreOffice for subtotals of tables created with this module

`_table_function_to_formula` receives the `$function` and the `$col_name`
and does:
`$formula = qq{SUBTOTAL($func_num,[$col_name])};`
https://github.com/jmcnamara/excel-writer-xlsx/blob/main/lib/Excel/Writer/XLSX/Worksheet.pm#L5046

This is not good enough for LibreOffice / OpenOffice
The explicit table name is needed, right before the column name between brackets

e.g. `=SUBTOTAL(109,current_table_name[column name])`
i.e. `$table{_name}` should be also passed to `_table_function_to_formula`
in order to be able to build a formula compatible with both MS Office and LibreOffice

**Comment by jmcnamara** [comment] 2022-05-04 23:01
Could you add a small complete working example that demonstrates the issue. Also, could you verify that the issue happens with Excel.

**Comment by arhak** [comment] 2022-05-04 23:20
```
#!/usr/bin/perl

# subtotals not working for LibreOffice
# https://github.com/jmcnamara/excel-writer-xlsx/issues/275

use strict;
use warnings;
use Excel::Writer::XLSX;

my $workbook  = Excel::Writer::XLSX->new( 'subtotals.xlsx' );
my $worksheet = $workbook->add_worksheet();

# Some sample data for the table.
my $data = [
    [ 'Apples',  10000, 5000, 8000, 6000 ],
    [ 'Pears',   2000,  3000, 4000, 5000 ],
    [ 'Bananas', 6000,  6000, 6500, 6000 ],
    [ 'Oranges', 500,   300,  200,  700 ],

];


###############################################################################
#
# Example
#
my $caption = 'Default table with data.';

# Set the columns widths.
$worksheet->set_column( 'B:G', 12 );

# Write the caption.
$worksheet->write( 'B1', $caption );

# Add a table to the worksheet.
$worksheet->add_table( 'B3:F7', {
    data => $data,
    columns => [{
        total_function => 'count',
    },{
        total_function => 'sum',
    }],
    total_row => 1,
});

$workbook->close();

__END__
```

**Comment by arhak** [comment] 2022-05-04 23:24
Resulting file (from above code) works OK in Excel (MS Office)
but not in LibreOffice

See attached sample files:
* resulting file from execution [subtotals.xlsx](https://github.com/jmcnamara/excel-writer-xlsx/files/8627926/subtotals.xlsx)
* manually edited to work in LibreOffice [subtotals manually added Table1 to subtotals (for LibreOffice).xlsx](https://github.com/jmcnamara/excel-writer-xlsx/files/8627927/subtotals.manually.added.Table1.to.subtotals.for.LibreOffice.xlsx)

OTOH these files can also be uploaded for instance to Google Drive and Sheets will also assimilate the latter, same as LibreOffice does,
but will have issue with the former, stating a "Formula parse error." for the "count" although not for the "sum"
(just FYI, not that Sheets should be a goal or anything, but I'm not aware of the specifics for XLSX)

**Comment by jmcnamara** [comment] 2022-05-04 23:38
What about this Excel generated file from the test suite: https://github.com/jmcnamara/excel-writer-xlsx/blob/main/t/regression/xlsx_files/table08.xlsx

Does in load in your version of LibreOffice?

**Comment by arhak** [comment] 2022-05-04 23:46
no, it doesn't

it shows a zero count both in Excel and LibreOffice (v7.3) because the table is empty
then when entering data into Column4
* Excel => subtotal updates with the count of non-empty cells
* LibreOffice => zero remains unchanged

if formula is manually edited to become `=SUBTOTAL(103,Table1[Column4])`
then it works for both Excel and LibreOffice

**Comment by jmcnamara** [comment] 2022-05-04 23:55
I checked myself with LibreOffice 6.4 (which is a bit old now). The Excel 2007 generated file (and other Excel 2007 generated file from the test suite appear to give the error you highlighted above.

So, to me, this looks like a Libreoffice issue with Excel 2007 files. Excel::Writer::XLSX is producing file in the same way as Excel 2007 and the original versions of the spec.

**Comment by jmcnamara** [comment] 2022-05-04 23:59
P.S. the explicit Table name format was added in later versions of Excel and the xlsx spec.

**Comment by jmcnamara** [comment] 2022-05-09 06:50
Closing for the reasons given above.

**Closed by jmcnamara** 2022-05-09 06:50 UTC
