### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by geekdad1** [jmcnamara/excel-writer-xlsx#179] opened 2016-11-23 22:53 UTC
It would be nice if there was a way to apply multiple formats to a specific cell.  for example: you might have a bold format, a color format, a border format, etc.  It would be useful to have a way to have a cell have just bold, bold and color, bold and border, color and border, etc. without having to create a multiple formats with all of the possible combinations that you need to use.  So if you could add two formats together in a write statement that would be useful.
The other way to do this might be to allow a write statement to add a format to a cell rather than replacing what's already there.  So you could write(1,1,"",$border); write(1,1,"text",$color); and get a cell with a border format and a color format.

**Comment by jmcnamara** [comment] 2016-11-24 13:26
Hi @geekdad1,

I think this is, more or less, a duplicate of #149 "Feature request: Format cells without writing new data". Even if it isn't an exact duplicate it would require the same type of internal infrastructure.

I agree that it would be a good idea, and it was planned as a feature, but realistically, it won't be implemented anytime soon.

I'll close this as a duplicate and you can add a +1 to #149 in case there are any duplicates.

John

**Closed by jmcnamara** 2016-11-24 13:26 UTC

**Comment by geekdad1** [comment] 2016-11-24 18:19
Great.  Thanks for the update.  I like the application and so I'll carry on with the way it works today.

 

Doug
