### ISSUE TITLE
Feature Request: Add Backgound image to Comment

### ISSUE THREAD

**Issue by piepiax** [jmcnamara/excel-writer-xlsx#245] opened 2019-10-21 13:03 UTC
Hi,
First of all, congrats for this wonderful package, very useful and almost complete.

I wrote a new issue / Feature request but it could be probably merged with the #188  as it's about add a background image to comments.

Indeed, I use a comment to insert image associated to a particular feature/value within a cell.
This is particularly useful to have a rapid visual insight when you mouse hover the cell
For the moment, I have to use a Macro (.xlsm) to edit this kind of comment and it would easier to have it directly when I create the .xlsx without any action by the user

Here an example what I talk about [Picture in Comment Example](https://trumpexcel.com/insert-picture-in-excel-comment/)

Thanks

**Comment by jmcnamara** [comment] 2019-10-21 13:13
Similar to a request in XlsxWriter: https://github.com/jmcnamara/XlsxWriter/issues/377

**Comment by jmcnamara** [comment] 2019-10-26 16:51
Closed as a duplicate of jmcnamara/XlsxWriter#377 They will both be closed at the same time (if they are closed).

**Closed by jmcnamara** 2019-10-26 16:51 UTC
Labels: feature request
