### ISSUE TITLE
Excel found an unreadable content issue

### ISSUE THREAD

**Issue by Hari3288** [jmcnamara/excel-writer-xlsx#123] opened 2015-03-13 10:45 UTC
Hi,

I have generated a excel file through perl script and it consist of around 80 tabs in it, When i try to open the excel file i am getting "Excel found an unreadable content issue" and due this the percentage calculation performed in excel got changed to actual values.

Can anyone please suggest whether its because of any upgrade issue.

Note: When i try to generate the excel with few number of rows this issue is not getting displayed.

Currently i am using "Excel-Writer-XLSX-0.12" version 0.12.

**Comment by jmcnamara** [comment] 2015-03-13 11:27
Can you try the following:
 
* Upgrade to the latest version of the module, which is 0.81.
* If the issue also happens with the latest version then try break the issue down into a small example program that demonstrates it. 

John

**Comment by Hari3288** [comment] 2015-03-13 11:36
Hi John,

Can you please let me know why this (Excel found an unreadable content) issue is happening in Perl?

**Comment by jmcnamara** [comment] 2015-03-13 11:52
> Can you please let me know why this (Excel found an unreadable content) issue is happening in Perl?

It is a general Excel error meaning that there is an XML error in the file.

See if an upgrade fixes it (your version is 4 years and 69 versions behind the current release.

If the upgrade doesn't fix the issue then try break the program down into a small program that demonstrates the issue, post it here, and I'll look into it.

John

**Comment by Hari3288** [comment] 2015-03-13 12:09
Hi john,

Could you please let me know how to upgrade the Excel writer to current version, Whether it requires any Admin level access? As i am using the system which is not having admin level access.

**Comment by jmcnamara** [comment] 2015-03-13 15:24
> Could you please let me know how to upgrade the Excel writer to current version, Whether it requires any Admin level access?

I can't really help with questions about installation permissions. I can only really answer questions related to the module.

If you need to test with the latest version there are a number of ways to install modules locally for testing. Google should show a few alternatives.

John

**Comment by Hari3288** [comment] 2015-03-13 15:40
Thanks John.

**Comment by Hari3288** [comment] 2015-03-16 10:42
John,

Could you please clarify us one more for the above issue.

We are using 2 unix servers one is the main server and one is for testing server in both the server "Excel Writer 0.12" Version are used but in main server we are getting the expected result but the server which we used for testing purpose we are getting the Excel found unreadable content issue, Hence could you please let us know why this differences occurs?

**Comment by jmcnamara** [comment] 2015-03-16 14:09
Hi,

It is hard to say what is the issue. Try running the following program on both systems to see what is different:

```perl
#!/usr/bin/perl

use strict;
use warnings;


print "\n    Perl version   : $]";
print "\n    OS name        : $^O";
print "\n    Module versions: (not all are required)\n";


my @modules = qw(
                  Excel::Writer::XLSX
                  Archive::Zip
                  File::Temp
                );


for my $module (@modules) {
    my $version;
    eval "require $module";

    if (not $@) {
        $version = $module->VERSION;
        $version = '(unknown)' if not defined $version;
    }
    else {
        $version = '(not installed)';
    }

    printf "%21s%-24s\t%s\n", "", $module, $version;
}

__END__

```

**Comment by jmcnamara** [comment] 2015-03-23 00:35
Closing. I hope you managed to resolve this issue.

**Closed by jmcnamara** 2015-03-23 00:35 UTC
Labels: question

**Comment by gminnick** [comment] 2015-05-14 13:48
I had the same issue.  For me, it was caused by using a format object that was created for another workbook.  When I discovered my error, the Excel error went away!

**Comment by jmcnamara** [comment] 2015-05-19 10:03
@gminnick Thanks for that the is good to know.

However, for anyone else who comes across this I would like to point out that it isn't necessarily the same issue. The "Excel found an unreadable content" error/warning is emitted by Excel for almost every possible issue in the file format.
